/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 92
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 59
#define ALIAS_COUNT 0
#define TOKEN_COUNT 25
#define EXTERNAL_TOKEN_COUNT 2
#define FIELD_COUNT 10
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 20
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  anon_sym_new = 2,
  anon_sym_entry = 3,
  anon_sym_type = 4,
  anon_sym_using = 5,
  anon_sym_data = 6,
  anon_sym_treasuretable = 7,
  anon_sym_CanMerge = 8,
  anon_sym_subtable = 9,
  anon_sym_object = 10,
  anon_sym_category = 11,
  anon_sym_COMMA = 12,
  anon_sym_equipment = 13,
  anon_sym_spellset = 14,
  anon_sym_itemgroup = 15,
  anon_sym_namegroup = 16,
  anon_sym_add = 17,
  anon_sym_COLON = 18,
  anon_sym_DQUOTE = 19,
  sym_string_content = 20,
  sym_number = 21,
  aux_sym_comment_token1 = 22,
  sym__newline = 23,
  sym__eof = 24,
  sym_source_file = 25,
  sym_stat_entry = 26,
  sym_entry_header = 27,
  sym_type_clause = 28,
  sym_using_clause = 29,
  sym_data_clause = 30,
  sym_treasure_table = 31,
  sym_treasure_table_header = 32,
  sym_merge_clause = 33,
  sym_treasure_subtable = 34,
  sym_subtable_header = 35,
  sym_object_clause = 36,
  sym_equipment_entry = 37,
  sym_equipment_header = 38,
  sym_named_block = 39,
  sym_named_block_header = 40,
  sym_add_clause = 41,
  sym_generic_statement = 42,
  sym_arguments = 43,
  sym_comma_values = 44,
  sym__argument = 45,
  sym_quoted_string = 46,
  sym_comment = 47,
  sym_trailing_comment = 48,
  sym__line_end = 49,
  sym__blank_line = 50,
  aux_sym_source_file_repeat1 = 51,
  aux_sym_stat_entry_repeat1 = 52,
  aux_sym_treasure_table_repeat1 = 53,
  aux_sym_treasure_subtable_repeat1 = 54,
  aux_sym_equipment_entry_repeat1 = 55,
  aux_sym_add_clause_repeat1 = 56,
  aux_sym_generic_statement_repeat1 = 57,
  aux_sym_comma_values_repeat1 = 58,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_new] = "new",
  [anon_sym_entry] = "entry",
  [anon_sym_type] = "type",
  [anon_sym_using] = "using",
  [anon_sym_data] = "data",
  [anon_sym_treasuretable] = "treasuretable",
  [anon_sym_CanMerge] = "identifier",
  [anon_sym_subtable] = "subtable",
  [anon_sym_object] = "object",
  [anon_sym_category] = "category",
  [anon_sym_COMMA] = ",",
  [anon_sym_equipment] = "equipment",
  [anon_sym_spellset] = "spellset",
  [anon_sym_itemgroup] = "itemgroup",
  [anon_sym_namegroup] = "namegroup",
  [anon_sym_add] = "add",
  [anon_sym_COLON] = ":",
  [anon_sym_DQUOTE] = "\"",
  [sym_string_content] = "string_content",
  [sym_number] = "number",
  [aux_sym_comment_token1] = "comment_token1",
  [sym__newline] = "_newline",
  [sym__eof] = "_eof",
  [sym_source_file] = "source_file",
  [sym_stat_entry] = "stat_entry",
  [sym_entry_header] = "entry_header",
  [sym_type_clause] = "type_clause",
  [sym_using_clause] = "using_clause",
  [sym_data_clause] = "data_clause",
  [sym_treasure_table] = "treasure_table",
  [sym_treasure_table_header] = "treasure_table_header",
  [sym_merge_clause] = "merge_clause",
  [sym_treasure_subtable] = "treasure_subtable",
  [sym_subtable_header] = "subtable_header",
  [sym_object_clause] = "object_clause",
  [sym_equipment_entry] = "equipment_entry",
  [sym_equipment_header] = "equipment_header",
  [sym_named_block] = "named_block",
  [sym_named_block_header] = "named_block_header",
  [sym_add_clause] = "add_clause",
  [sym_generic_statement] = "generic_statement",
  [sym_arguments] = "arguments",
  [sym_comma_values] = "comma_values",
  [sym__argument] = "_argument",
  [sym_quoted_string] = "quoted_string",
  [sym_comment] = "comment",
  [sym_trailing_comment] = "trailing_comment",
  [sym__line_end] = "_line_end",
  [sym__blank_line] = "_blank_line",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_stat_entry_repeat1] = "stat_entry_repeat1",
  [aux_sym_treasure_table_repeat1] = "treasure_table_repeat1",
  [aux_sym_treasure_subtable_repeat1] = "treasure_subtable_repeat1",
  [aux_sym_equipment_entry_repeat1] = "equipment_entry_repeat1",
  [aux_sym_add_clause_repeat1] = "add_clause_repeat1",
  [aux_sym_generic_statement_repeat1] = "generic_statement_repeat1",
  [aux_sym_comma_values_repeat1] = "comma_values_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_new] = anon_sym_new,
  [anon_sym_entry] = anon_sym_entry,
  [anon_sym_type] = anon_sym_type,
  [anon_sym_using] = anon_sym_using,
  [anon_sym_data] = anon_sym_data,
  [anon_sym_treasuretable] = anon_sym_treasuretable,
  [anon_sym_CanMerge] = sym_identifier,
  [anon_sym_subtable] = anon_sym_subtable,
  [anon_sym_object] = anon_sym_object,
  [anon_sym_category] = anon_sym_category,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_equipment] = anon_sym_equipment,
  [anon_sym_spellset] = anon_sym_spellset,
  [anon_sym_itemgroup] = anon_sym_itemgroup,
  [anon_sym_namegroup] = anon_sym_namegroup,
  [anon_sym_add] = anon_sym_add,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [sym_string_content] = sym_string_content,
  [sym_number] = sym_number,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [sym__newline] = sym__newline,
  [sym__eof] = sym__eof,
  [sym_source_file] = sym_source_file,
  [sym_stat_entry] = sym_stat_entry,
  [sym_entry_header] = sym_entry_header,
  [sym_type_clause] = sym_type_clause,
  [sym_using_clause] = sym_using_clause,
  [sym_data_clause] = sym_data_clause,
  [sym_treasure_table] = sym_treasure_table,
  [sym_treasure_table_header] = sym_treasure_table_header,
  [sym_merge_clause] = sym_merge_clause,
  [sym_treasure_subtable] = sym_treasure_subtable,
  [sym_subtable_header] = sym_subtable_header,
  [sym_object_clause] = sym_object_clause,
  [sym_equipment_entry] = sym_equipment_entry,
  [sym_equipment_header] = sym_equipment_header,
  [sym_named_block] = sym_named_block,
  [sym_named_block_header] = sym_named_block_header,
  [sym_add_clause] = sym_add_clause,
  [sym_generic_statement] = sym_generic_statement,
  [sym_arguments] = sym_arguments,
  [sym_comma_values] = sym_comma_values,
  [sym__argument] = sym__argument,
  [sym_quoted_string] = sym_quoted_string,
  [sym_comment] = sym_comment,
  [sym_trailing_comment] = sym_trailing_comment,
  [sym__line_end] = sym__line_end,
  [sym__blank_line] = sym__blank_line,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_stat_entry_repeat1] = aux_sym_stat_entry_repeat1,
  [aux_sym_treasure_table_repeat1] = aux_sym_treasure_table_repeat1,
  [aux_sym_treasure_subtable_repeat1] = aux_sym_treasure_subtable_repeat1,
  [aux_sym_equipment_entry_repeat1] = aux_sym_equipment_entry_repeat1,
  [aux_sym_add_clause_repeat1] = aux_sym_add_clause_repeat1,
  [aux_sym_generic_statement_repeat1] = aux_sym_generic_statement_repeat1,
  [aux_sym_comma_values_repeat1] = aux_sym_comma_values_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_new] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_entry] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_type] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_using] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_data] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_treasuretable] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_CanMerge] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_subtable] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_object] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_category] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_equipment] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_spellset] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_itemgroup] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_namegroup] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_add] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym_string_content] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [sym__eof] = {
    .visible = false,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_stat_entry] = {
    .visible = true,
    .named = true,
  },
  [sym_entry_header] = {
    .visible = true,
    .named = true,
  },
  [sym_type_clause] = {
    .visible = true,
    .named = true,
  },
  [sym_using_clause] = {
    .visible = true,
    .named = true,
  },
  [sym_data_clause] = {
    .visible = true,
    .named = true,
  },
  [sym_treasure_table] = {
    .visible = true,
    .named = true,
  },
  [sym_treasure_table_header] = {
    .visible = true,
    .named = true,
  },
  [sym_merge_clause] = {
    .visible = true,
    .named = true,
  },
  [sym_treasure_subtable] = {
    .visible = true,
    .named = true,
  },
  [sym_subtable_header] = {
    .visible = true,
    .named = true,
  },
  [sym_object_clause] = {
    .visible = true,
    .named = true,
  },
  [sym_equipment_entry] = {
    .visible = true,
    .named = true,
  },
  [sym_equipment_header] = {
    .visible = true,
    .named = true,
  },
  [sym_named_block] = {
    .visible = true,
    .named = true,
  },
  [sym_named_block_header] = {
    .visible = true,
    .named = true,
  },
  [sym_add_clause] = {
    .visible = true,
    .named = true,
  },
  [sym_generic_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_arguments] = {
    .visible = true,
    .named = true,
  },
  [sym_comma_values] = {
    .visible = true,
    .named = true,
  },
  [sym__argument] = {
    .visible = false,
    .named = true,
  },
  [sym_quoted_string] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_trailing_comment] = {
    .visible = true,
    .named = true,
  },
  [sym__line_end] = {
    .visible = false,
    .named = true,
  },
  [sym__blank_line] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_stat_entry_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_treasure_table_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_treasure_subtable_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_equipment_entry_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_add_clause_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_generic_statement_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_comma_values_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_arguments = 1,
  field_category = 2,
  field_command = 3,
  field_content = 4,
  field_distribution = 5,
  field_kind = 6,
  field_name = 7,
  field_qualifier = 8,
  field_value = 9,
  field_weights = 10,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_arguments] = "arguments",
  [field_category] = "category",
  [field_command] = "command",
  [field_content] = "content",
  [field_distribution] = "distribution",
  [field_kind] = "kind",
  [field_name] = "name",
  [field_qualifier] = "qualifier",
  [field_value] = "value",
  [field_weights] = "weights",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 2},
  [4] = {.index = 4, .length = 2},
  [5] = {.index = 6, .length = 1},
  [6] = {.index = 7, .length = 2},
  [7] = {.index = 9, .length = 1},
  [8] = {.index = 10, .length = 1},
  [9] = {.index = 11, .length = 2},
  [10] = {.index = 13, .length = 1},
  [11] = {.index = 14, .length = 1},
  [12] = {.index = 15, .length = 2},
  [13] = {.index = 17, .length = 1},
  [14] = {.index = 18, .length = 2},
  [15] = {.index = 20, .length = 2},
  [16] = {.index = 22, .length = 2},
  [17] = {.index = 24, .length = 1},
  [18] = {.index = 25, .length = 3},
  [19] = {.index = 28, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_arguments, 0},
  [1] =
    {field_command, 0},
  [2] =
    {field_arguments, 1, .inherited = true},
    {field_command, 0},
  [4] =
    {field_arguments, 0, .inherited = true},
    {field_arguments, 1, .inherited = true},
  [6] =
    {field_name, 2},
  [7] =
    {field_kind, 1},
    {field_name, 2},
  [9] =
    {field_content, 1},
  [10] =
    {field_value, 1},
  [11] =
    {field_name, 0},
    {field_value, 1},
  [13] =
    {field_qualifier, 0},
  [14] =
    {field_kind, 1},
  [15] =
    {field_name, 1},
    {field_value, 2},
  [17] =
    {field_distribution, 2},
  [18] =
    {field_arguments, 2},
    {field_kind, 1},
  [20] =
    {field_kind, 1},
    {field_qualifier, 2, .inherited = true},
  [22] =
    {field_qualifier, 0, .inherited = true},
    {field_qualifier, 1, .inherited = true},
  [24] =
    {field_category, 2},
  [25] =
    {field_arguments, 3},
    {field_kind, 1},
    {field_qualifier, 2, .inherited = true},
  [28] =
    {field_category, 2},
    {field_weights, 4},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 70,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 26,
  [89] = 28,
  [90] = 90,
  [91] = 83,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(6);
      if (lookahead == '"') ADVANCE(9);
      if (lookahead == ',') ADVANCE(7);
      if (lookahead == '-') ADVANCE(2);
      if (lookahead == '.') ADVANCE(4);
      if (lookahead == '/') ADVANCE(3);
      if (lookahead == ':') ADVANCE(8);
      if (lookahead == '\t' ||
          lookahead == '\f' ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(13);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(12);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(9);
      if (lookahead == '\\') ADVANCE(5);
      if (lookahead == '\t' ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(10);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\f' &&
          lookahead != '\r' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(11);
      END_STATE();
    case 2:
      if (lookahead == '.') ADVANCE(4);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(13);
      END_STATE();
    case 3:
      if (lookahead == '/') ADVANCE(15);
      END_STATE();
    case 4:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(14);
      END_STATE();
    case 5:
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(11);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(sym_string_content);
      if (lookahead == '\\') ADVANCE(5);
      if (lookahead == '\t' ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(10);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\f' &&
          lookahead != '\r' &&
          lookahead != '"' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(11);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym_string_content);
      if (lookahead == '\\') ADVANCE(5);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '"' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(11);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(12);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(4);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(13);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(14);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(15);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ADVANCE_MAP(
        'C', 1,
        'a', 2,
        'c', 3,
        'd', 4,
        'e', 5,
        'i', 6,
        'n', 7,
        'o', 8,
        's', 9,
        't', 10,
        'u', 11,
      );
      if (lookahead == '\t' ||
          lookahead == '\f' ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'a') ADVANCE(12);
      END_STATE();
    case 2:
      if (lookahead == 'd') ADVANCE(13);
      END_STATE();
    case 3:
      if (lookahead == 'a') ADVANCE(14);
      END_STATE();
    case 4:
      if (lookahead == 'a') ADVANCE(15);
      END_STATE();
    case 5:
      if (lookahead == 'n') ADVANCE(16);
      if (lookahead == 'q') ADVANCE(17);
      END_STATE();
    case 6:
      if (lookahead == 't') ADVANCE(18);
      END_STATE();
    case 7:
      if (lookahead == 'a') ADVANCE(19);
      if (lookahead == 'e') ADVANCE(20);
      END_STATE();
    case 8:
      if (lookahead == 'b') ADVANCE(21);
      END_STATE();
    case 9:
      if (lookahead == 'p') ADVANCE(22);
      if (lookahead == 'u') ADVANCE(23);
      END_STATE();
    case 10:
      if (lookahead == 'r') ADVANCE(24);
      if (lookahead == 'y') ADVANCE(25);
      END_STATE();
    case 11:
      if (lookahead == 's') ADVANCE(26);
      END_STATE();
    case 12:
      if (lookahead == 'n') ADVANCE(27);
      END_STATE();
    case 13:
      if (lookahead == 'd') ADVANCE(28);
      END_STATE();
    case 14:
      if (lookahead == 't') ADVANCE(29);
      END_STATE();
    case 15:
      if (lookahead == 't') ADVANCE(30);
      END_STATE();
    case 16:
      if (lookahead == 't') ADVANCE(31);
      END_STATE();
    case 17:
      if (lookahead == 'u') ADVANCE(32);
      END_STATE();
    case 18:
      if (lookahead == 'e') ADVANCE(33);
      END_STATE();
    case 19:
      if (lookahead == 'm') ADVANCE(34);
      END_STATE();
    case 20:
      if (lookahead == 'w') ADVANCE(35);
      END_STATE();
    case 21:
      if (lookahead == 'j') ADVANCE(36);
      END_STATE();
    case 22:
      if (lookahead == 'e') ADVANCE(37);
      END_STATE();
    case 23:
      if (lookahead == 'b') ADVANCE(38);
      END_STATE();
    case 24:
      if (lookahead == 'e') ADVANCE(39);
      END_STATE();
    case 25:
      if (lookahead == 'p') ADVANCE(40);
      END_STATE();
    case 26:
      if (lookahead == 'i') ADVANCE(41);
      END_STATE();
    case 27:
      if (lookahead == 'M') ADVANCE(42);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_add);
      END_STATE();
    case 29:
      if (lookahead == 'e') ADVANCE(43);
      END_STATE();
    case 30:
      if (lookahead == 'a') ADVANCE(44);
      END_STATE();
    case 31:
      if (lookahead == 'r') ADVANCE(45);
      END_STATE();
    case 32:
      if (lookahead == 'i') ADVANCE(46);
      END_STATE();
    case 33:
      if (lookahead == 'm') ADVANCE(47);
      END_STATE();
    case 34:
      if (lookahead == 'e') ADVANCE(48);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_new);
      END_STATE();
    case 36:
      if (lookahead == 'e') ADVANCE(49);
      END_STATE();
    case 37:
      if (lookahead == 'l') ADVANCE(50);
      END_STATE();
    case 38:
      if (lookahead == 't') ADVANCE(51);
      END_STATE();
    case 39:
      if (lookahead == 'a') ADVANCE(52);
      END_STATE();
    case 40:
      if (lookahead == 'e') ADVANCE(53);
      END_STATE();
    case 41:
      if (lookahead == 'n') ADVANCE(54);
      END_STATE();
    case 42:
      if (lookahead == 'e') ADVANCE(55);
      END_STATE();
    case 43:
      if (lookahead == 'g') ADVANCE(56);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_data);
      END_STATE();
    case 45:
      if (lookahead == 'y') ADVANCE(57);
      END_STATE();
    case 46:
      if (lookahead == 'p') ADVANCE(58);
      END_STATE();
    case 47:
      if (lookahead == 'g') ADVANCE(59);
      END_STATE();
    case 48:
      if (lookahead == 'g') ADVANCE(60);
      END_STATE();
    case 49:
      if (lookahead == 'c') ADVANCE(61);
      END_STATE();
    case 50:
      if (lookahead == 'l') ADVANCE(62);
      END_STATE();
    case 51:
      if (lookahead == 'a') ADVANCE(63);
      END_STATE();
    case 52:
      if (lookahead == 's') ADVANCE(64);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_type);
      END_STATE();
    case 54:
      if (lookahead == 'g') ADVANCE(65);
      END_STATE();
    case 55:
      if (lookahead == 'r') ADVANCE(66);
      END_STATE();
    case 56:
      if (lookahead == 'o') ADVANCE(67);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_entry);
      END_STATE();
    case 58:
      if (lookahead == 'm') ADVANCE(68);
      END_STATE();
    case 59:
      if (lookahead == 'r') ADVANCE(69);
      END_STATE();
    case 60:
      if (lookahead == 'r') ADVANCE(70);
      END_STATE();
    case 61:
      if (lookahead == 't') ADVANCE(71);
      END_STATE();
    case 62:
      if (lookahead == 's') ADVANCE(72);
      END_STATE();
    case 63:
      if (lookahead == 'b') ADVANCE(73);
      END_STATE();
    case 64:
      if (lookahead == 'u') ADVANCE(74);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_using);
      END_STATE();
    case 66:
      if (lookahead == 'g') ADVANCE(75);
      END_STATE();
    case 67:
      if (lookahead == 'r') ADVANCE(76);
      END_STATE();
    case 68:
      if (lookahead == 'e') ADVANCE(77);
      END_STATE();
    case 69:
      if (lookahead == 'o') ADVANCE(78);
      END_STATE();
    case 70:
      if (lookahead == 'o') ADVANCE(79);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_object);
      END_STATE();
    case 72:
      if (lookahead == 'e') ADVANCE(80);
      END_STATE();
    case 73:
      if (lookahead == 'l') ADVANCE(81);
      END_STATE();
    case 74:
      if (lookahead == 'r') ADVANCE(82);
      END_STATE();
    case 75:
      if (lookahead == 'e') ADVANCE(83);
      END_STATE();
    case 76:
      if (lookahead == 'y') ADVANCE(84);
      END_STATE();
    case 77:
      if (lookahead == 'n') ADVANCE(85);
      END_STATE();
    case 78:
      if (lookahead == 'u') ADVANCE(86);
      END_STATE();
    case 79:
      if (lookahead == 'u') ADVANCE(87);
      END_STATE();
    case 80:
      if (lookahead == 't') ADVANCE(88);
      END_STATE();
    case 81:
      if (lookahead == 'e') ADVANCE(89);
      END_STATE();
    case 82:
      if (lookahead == 'e') ADVANCE(90);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(anon_sym_CanMerge);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(anon_sym_category);
      END_STATE();
    case 85:
      if (lookahead == 't') ADVANCE(91);
      END_STATE();
    case 86:
      if (lookahead == 'p') ADVANCE(92);
      END_STATE();
    case 87:
      if (lookahead == 'p') ADVANCE(93);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(anon_sym_spellset);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(anon_sym_subtable);
      END_STATE();
    case 90:
      if (lookahead == 't') ADVANCE(94);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(anon_sym_equipment);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(anon_sym_itemgroup);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(anon_sym_namegroup);
      END_STATE();
    case 94:
      if (lookahead == 'a') ADVANCE(95);
      END_STATE();
    case 95:
      if (lookahead == 'b') ADVANCE(96);
      END_STATE();
    case 96:
      if (lookahead == 'l') ADVANCE(97);
      END_STATE();
    case 97:
      if (lookahead == 'e') ADVANCE(98);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(anon_sym_treasuretable);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 0, .external_lex_state = 2},
  [2] = {.lex_state = 0, .external_lex_state = 2},
  [3] = {.lex_state = 0, .external_lex_state = 2},
  [4] = {.lex_state = 0, .external_lex_state = 2},
  [5] = {.lex_state = 0, .external_lex_state = 2},
  [6] = {.lex_state = 0, .external_lex_state = 2},
  [7] = {.lex_state = 0, .external_lex_state = 1},
  [8] = {.lex_state = 0, .external_lex_state = 1},
  [9] = {.lex_state = 0, .external_lex_state = 2},
  [10] = {.lex_state = 0, .external_lex_state = 2},
  [11] = {.lex_state = 0, .external_lex_state = 2},
  [12] = {.lex_state = 0, .external_lex_state = 2},
  [13] = {.lex_state = 0, .external_lex_state = 2},
  [14] = {.lex_state = 0, .external_lex_state = 2},
  [15] = {.lex_state = 0, .external_lex_state = 1},
  [16] = {.lex_state = 0, .external_lex_state = 2},
  [17] = {.lex_state = 0, .external_lex_state = 1},
  [18] = {.lex_state = 0, .external_lex_state = 2},
  [19] = {.lex_state = 0, .external_lex_state = 1},
  [20] = {.lex_state = 0, .external_lex_state = 2},
  [21] = {.lex_state = 0, .external_lex_state = 2},
  [22] = {.lex_state = 0, .external_lex_state = 2},
  [23] = {.lex_state = 0, .external_lex_state = 2},
  [24] = {.lex_state = 0, .external_lex_state = 2},
  [25] = {.lex_state = 0, .external_lex_state = 1},
  [26] = {.lex_state = 0, .external_lex_state = 1},
  [27] = {.lex_state = 0, .external_lex_state = 2},
  [28] = {.lex_state = 0, .external_lex_state = 1},
  [29] = {.lex_state = 0, .external_lex_state = 2},
  [30] = {.lex_state = 0, .external_lex_state = 2},
  [31] = {.lex_state = 0, .external_lex_state = 2},
  [32] = {.lex_state = 0, .external_lex_state = 2},
  [33] = {.lex_state = 0, .external_lex_state = 1},
  [34] = {.lex_state = 0, .external_lex_state = 2},
  [35] = {.lex_state = 0, .external_lex_state = 2},
  [36] = {.lex_state = 0, .external_lex_state = 2},
  [37] = {.lex_state = 0, .external_lex_state = 2},
  [38] = {.lex_state = 0, .external_lex_state = 2},
  [39] = {.lex_state = 0, .external_lex_state = 1},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0, .external_lex_state = 2},
  [42] = {.lex_state = 0, .external_lex_state = 2},
  [43] = {.lex_state = 0, .external_lex_state = 1},
  [44] = {.lex_state = 0, .external_lex_state = 2},
  [45] = {.lex_state = 0, .external_lex_state = 2},
  [46] = {.lex_state = 0, .external_lex_state = 2},
  [47] = {.lex_state = 0, .external_lex_state = 1},
  [48] = {.lex_state = 0, .external_lex_state = 1},
  [49] = {.lex_state = 0, .external_lex_state = 1},
  [50] = {.lex_state = 0, .external_lex_state = 1},
  [51] = {.lex_state = 0, .external_lex_state = 1},
  [52] = {.lex_state = 0, .external_lex_state = 1},
  [53] = {.lex_state = 0, .external_lex_state = 1},
  [54] = {.lex_state = 0, .external_lex_state = 1},
  [55] = {.lex_state = 0, .external_lex_state = 1},
  [56] = {.lex_state = 0, .external_lex_state = 2},
  [57] = {.lex_state = 0, .external_lex_state = 2},
  [58] = {.lex_state = 0, .external_lex_state = 1},
  [59] = {.lex_state = 0, .external_lex_state = 1},
  [60] = {.lex_state = 0, .external_lex_state = 1},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0, .external_lex_state = 1},
  [63] = {.lex_state = 0, .external_lex_state = 1},
  [64] = {.lex_state = 0, .external_lex_state = 1},
  [65] = {.lex_state = 0, .external_lex_state = 1},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0, .external_lex_state = 1},
  [68] = {.lex_state = 0, .external_lex_state = 1},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 1},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0, .external_lex_state = 1},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0, .external_lex_state = 1},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 1},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_new] = ACTIONS(1),
    [anon_sym_entry] = ACTIONS(1),
    [anon_sym_type] = ACTIONS(1),
    [anon_sym_using] = ACTIONS(1),
    [anon_sym_data] = ACTIONS(1),
    [anon_sym_treasuretable] = ACTIONS(1),
    [anon_sym_CanMerge] = ACTIONS(1),
    [anon_sym_subtable] = ACTIONS(1),
    [anon_sym_object] = ACTIONS(1),
    [anon_sym_category] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_equipment] = ACTIONS(1),
    [anon_sym_spellset] = ACTIONS(1),
    [anon_sym_itemgroup] = ACTIONS(1),
    [anon_sym_namegroup] = ACTIONS(1),
    [anon_sym_add] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [aux_sym_comment_token1] = ACTIONS(1),
    [sym__newline] = ACTIONS(1),
    [sym__eof] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(90),
    [sym_stat_entry] = STATE(2),
    [sym_entry_header] = STATE(6),
    [sym_treasure_table] = STATE(2),
    [sym_treasure_table_header] = STATE(10),
    [sym_equipment_entry] = STATE(2),
    [sym_equipment_header] = STATE(24),
    [sym_named_block] = STATE(2),
    [sym_named_block_header] = STATE(22),
    [sym_generic_statement] = STATE(2),
    [sym_comment] = STATE(2),
    [sym__blank_line] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_identifier] = ACTIONS(5),
    [anon_sym_new] = ACTIONS(7),
    [aux_sym_comment_token1] = ACTIONS(9),
    [sym__newline] = ACTIONS(11),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 10,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_new,
    ACTIONS(9), 1,
      aux_sym_comment_token1,
    ACTIONS(13), 1,
      ts_builtin_sym_end,
    ACTIONS(15), 1,
      sym__newline,
    STATE(6), 1,
      sym_entry_header,
    STATE(10), 1,
      sym_treasure_table_header,
    STATE(22), 1,
      sym_named_block_header,
    STATE(24), 1,
      sym_equipment_header,
    STATE(3), 8,
      sym_stat_entry,
      sym_treasure_table,
      sym_equipment_entry,
      sym_named_block,
      sym_generic_statement,
      sym_comment,
      sym__blank_line,
      aux_sym_source_file_repeat1,
  [38] = 10,
    ACTIONS(17), 1,
      ts_builtin_sym_end,
    ACTIONS(19), 1,
      sym_identifier,
    ACTIONS(22), 1,
      anon_sym_new,
    ACTIONS(25), 1,
      aux_sym_comment_token1,
    ACTIONS(28), 1,
      sym__newline,
    STATE(6), 1,
      sym_entry_header,
    STATE(10), 1,
      sym_treasure_table_header,
    STATE(22), 1,
      sym_named_block_header,
    STATE(24), 1,
      sym_equipment_header,
    STATE(3), 8,
      sym_stat_entry,
      sym_treasure_table,
      sym_equipment_entry,
      sym_named_block,
      sym_generic_statement,
      sym_comment,
      sym__blank_line,
      aux_sym_source_file_repeat1,
  [76] = 8,
    ACTIONS(33), 1,
      sym_identifier,
    ACTIONS(35), 1,
      anon_sym_type,
    ACTIONS(38), 1,
      anon_sym_using,
    ACTIONS(41), 1,
      anon_sym_data,
    ACTIONS(44), 1,
      aux_sym_comment_token1,
    ACTIONS(47), 1,
      sym__newline,
    ACTIONS(31), 2,
      ts_builtin_sym_end,
      anon_sym_new,
    STATE(4), 6,
      sym_type_clause,
      sym_using_clause,
      sym_data_clause,
      sym_comment,
      sym__blank_line,
      aux_sym_stat_entry_repeat1,
  [107] = 8,
    ACTIONS(52), 1,
      sym_identifier,
    ACTIONS(54), 1,
      anon_sym_type,
    ACTIONS(56), 1,
      anon_sym_using,
    ACTIONS(58), 1,
      anon_sym_data,
    ACTIONS(60), 1,
      aux_sym_comment_token1,
    ACTIONS(63), 1,
      sym__newline,
    ACTIONS(50), 2,
      ts_builtin_sym_end,
      anon_sym_new,
    STATE(4), 6,
      sym_type_clause,
      sym_using_clause,
      sym_data_clause,
      sym_comment,
      sym__blank_line,
      aux_sym_stat_entry_repeat1,
  [138] = 8,
    ACTIONS(54), 1,
      anon_sym_type,
    ACTIONS(56), 1,
      anon_sym_using,
    ACTIONS(58), 1,
      anon_sym_data,
    ACTIONS(68), 1,
      sym_identifier,
    ACTIONS(70), 1,
      aux_sym_comment_token1,
    ACTIONS(73), 1,
      sym__newline,
    ACTIONS(66), 2,
      ts_builtin_sym_end,
      anon_sym_new,
    STATE(5), 6,
      sym_type_clause,
      sym_using_clause,
      sym_data_clause,
      sym_comment,
      sym__blank_line,
      aux_sym_stat_entry_repeat1,
  [169] = 8,
    ACTIONS(78), 1,
      anon_sym_DQUOTE,
    ACTIONS(80), 1,
      aux_sym_comment_token1,
    STATE(15), 1,
      aux_sym_generic_statement_repeat1,
    STATE(57), 1,
      sym__line_end,
    STATE(73), 1,
      sym_trailing_comment,
    ACTIONS(82), 2,
      sym__newline,
      sym__eof,
    STATE(25), 2,
      sym__argument,
      sym_quoted_string,
    ACTIONS(76), 4,
      anon_sym_COMMA,
      anon_sym_COLON,
      sym_identifier,
      sym_number,
  [199] = 8,
    ACTIONS(78), 1,
      anon_sym_DQUOTE,
    ACTIONS(80), 1,
      aux_sym_comment_token1,
    STATE(7), 1,
      aux_sym_generic_statement_repeat1,
    STATE(56), 1,
      sym__line_end,
    STATE(73), 1,
      sym_trailing_comment,
    ACTIONS(84), 2,
      sym__newline,
      sym__eof,
    STATE(25), 2,
      sym__argument,
      sym_quoted_string,
    ACTIONS(76), 4,
      anon_sym_COMMA,
      anon_sym_COLON,
      sym_identifier,
      sym_number,
  [229] = 8,
    ACTIONS(86), 1,
      ts_builtin_sym_end,
    ACTIONS(88), 1,
      sym_identifier,
    ACTIONS(90), 1,
      anon_sym_new,
    ACTIONS(93), 1,
      anon_sym_CanMerge,
    ACTIONS(95), 1,
      aux_sym_comment_token1,
    ACTIONS(98), 1,
      sym__newline,
    STATE(13), 1,
      sym_subtable_header,
    STATE(11), 5,
      sym_merge_clause,
      sym_treasure_subtable,
      sym_comment,
      sym__blank_line,
      aux_sym_treasure_table_repeat1,
  [258] = 8,
    ACTIONS(93), 1,
      anon_sym_CanMerge,
    ACTIONS(101), 1,
      ts_builtin_sym_end,
    ACTIONS(103), 1,
      sym_identifier,
    ACTIONS(105), 1,
      anon_sym_new,
    ACTIONS(108), 1,
      aux_sym_comment_token1,
    ACTIONS(111), 1,
      sym__newline,
    STATE(13), 1,
      sym_subtable_header,
    STATE(9), 5,
      sym_merge_clause,
      sym_treasure_subtable,
      sym_comment,
      sym__blank_line,
      aux_sym_treasure_table_repeat1,
  [287] = 8,
    ACTIONS(114), 1,
      ts_builtin_sym_end,
    ACTIONS(116), 1,
      sym_identifier,
    ACTIONS(118), 1,
      anon_sym_new,
    ACTIONS(121), 1,
      anon_sym_CanMerge,
    ACTIONS(124), 1,
      aux_sym_comment_token1,
    ACTIONS(127), 1,
      sym__newline,
    STATE(13), 1,
      sym_subtable_header,
    STATE(11), 5,
      sym_merge_clause,
      sym_treasure_subtable,
      sym_comment,
      sym__blank_line,
      aux_sym_treasure_table_repeat1,
  [316] = 2,
    ACTIONS(132), 1,
      sym_identifier,
    ACTIONS(130), 10,
      sym__newline,
      ts_builtin_sym_end,
      anon_sym_new,
      anon_sym_type,
      anon_sym_using,
      anon_sym_data,
      anon_sym_CanMerge,
      anon_sym_object,
      anon_sym_add,
      aux_sym_comment_token1,
  [332] = 6,
    ACTIONS(136), 1,
      sym_identifier,
    ACTIONS(138), 1,
      anon_sym_object,
    ACTIONS(140), 1,
      aux_sym_comment_token1,
    ACTIONS(143), 1,
      sym__newline,
    ACTIONS(134), 3,
      ts_builtin_sym_end,
      anon_sym_new,
      anon_sym_CanMerge,
    STATE(16), 4,
      sym_object_clause,
      sym_comment,
      sym__blank_line,
      aux_sym_treasure_subtable_repeat1,
  [356] = 2,
    ACTIONS(148), 1,
      sym_identifier,
    ACTIONS(146), 10,
      sym__newline,
      ts_builtin_sym_end,
      anon_sym_new,
      anon_sym_type,
      anon_sym_using,
      anon_sym_data,
      anon_sym_CanMerge,
      anon_sym_object,
      anon_sym_add,
      aux_sym_comment_token1,
  [372] = 5,
    ACTIONS(153), 1,
      anon_sym_DQUOTE,
    STATE(15), 1,
      aux_sym_generic_statement_repeat1,
    STATE(25), 2,
      sym__argument,
      sym_quoted_string,
    ACTIONS(156), 3,
      sym__newline,
      sym__eof,
      aux_sym_comment_token1,
    ACTIONS(150), 4,
      anon_sym_COMMA,
      anon_sym_COLON,
      sym_identifier,
      sym_number,
  [394] = 6,
    ACTIONS(138), 1,
      anon_sym_object,
    ACTIONS(160), 1,
      sym_identifier,
    ACTIONS(162), 1,
      aux_sym_comment_token1,
    ACTIONS(165), 1,
      sym__newline,
    ACTIONS(158), 3,
      ts_builtin_sym_end,
      anon_sym_new,
      anon_sym_CanMerge,
    STATE(18), 4,
      sym_object_clause,
      sym_comment,
      sym__blank_line,
      aux_sym_treasure_subtable_repeat1,
  [418] = 10,
    ACTIONS(78), 1,
      anon_sym_DQUOTE,
    ACTIONS(80), 1,
      aux_sym_comment_token1,
    ACTIONS(168), 1,
      sym_identifier,
    ACTIONS(170), 1,
      sym_number,
    STATE(19), 1,
      aux_sym_add_clause_repeat1,
    STATE(45), 1,
      sym__line_end,
    STATE(53), 1,
      sym_arguments,
    STATE(68), 1,
      sym_quoted_string,
    STATE(73), 1,
      sym_trailing_comment,
    ACTIONS(172), 2,
      sym__newline,
      sym__eof,
  [450] = 6,
    ACTIONS(176), 1,
      sym_identifier,
    ACTIONS(178), 1,
      anon_sym_object,
    ACTIONS(181), 1,
      aux_sym_comment_token1,
    ACTIONS(184), 1,
      sym__newline,
    ACTIONS(174), 3,
      ts_builtin_sym_end,
      anon_sym_new,
      anon_sym_CanMerge,
    STATE(18), 4,
      sym_object_clause,
      sym_comment,
      sym__blank_line,
      aux_sym_treasure_subtable_repeat1,
  [474] = 10,
    ACTIONS(78), 1,
      anon_sym_DQUOTE,
    ACTIONS(80), 1,
      aux_sym_comment_token1,
    ACTIONS(168), 1,
      sym_identifier,
    ACTIONS(170), 1,
      sym_number,
    STATE(33), 1,
      aux_sym_add_clause_repeat1,
    STATE(41), 1,
      sym__line_end,
    STATE(58), 1,
      sym_arguments,
    STATE(68), 1,
      sym_quoted_string,
    STATE(73), 1,
      sym_trailing_comment,
    ACTIONS(187), 2,
      sym__newline,
      sym__eof,
  [506] = 6,
    ACTIONS(191), 1,
      sym_identifier,
    ACTIONS(193), 1,
      anon_sym_add,
    ACTIONS(195), 1,
      aux_sym_comment_token1,
    ACTIONS(198), 1,
      sym__newline,
    ACTIONS(189), 2,
      ts_builtin_sym_end,
      anon_sym_new,
    STATE(23), 4,
      sym_add_clause,
      sym_comment,
      sym__blank_line,
      aux_sym_equipment_entry_repeat1,
  [529] = 6,
    ACTIONS(193), 1,
      anon_sym_add,
    ACTIONS(203), 1,
      sym_identifier,
    ACTIONS(205), 1,
      aux_sym_comment_token1,
    ACTIONS(208), 1,
      sym__newline,
    ACTIONS(201), 2,
      ts_builtin_sym_end,
      anon_sym_new,
    STATE(23), 4,
      sym_add_clause,
      sym_comment,
      sym__blank_line,
      aux_sym_equipment_entry_repeat1,
  [552] = 6,
    ACTIONS(193), 1,
      anon_sym_add,
    ACTIONS(213), 1,
      sym_identifier,
    ACTIONS(215), 1,
      aux_sym_comment_token1,
    ACTIONS(218), 1,
      sym__newline,
    ACTIONS(211), 2,
      ts_builtin_sym_end,
      anon_sym_new,
    STATE(20), 4,
      sym_add_clause,
      sym_comment,
      sym__blank_line,
      aux_sym_equipment_entry_repeat1,
  [575] = 6,
    ACTIONS(223), 1,
      sym_identifier,
    ACTIONS(225), 1,
      anon_sym_add,
    ACTIONS(228), 1,
      aux_sym_comment_token1,
    ACTIONS(231), 1,
      sym__newline,
    ACTIONS(221), 2,
      ts_builtin_sym_end,
      anon_sym_new,
    STATE(23), 4,
      sym_add_clause,
      sym_comment,
      sym__blank_line,
      aux_sym_equipment_entry_repeat1,
  [598] = 6,
    ACTIONS(193), 1,
      anon_sym_add,
    ACTIONS(236), 1,
      sym_identifier,
    ACTIONS(238), 1,
      aux_sym_comment_token1,
    ACTIONS(241), 1,
      sym__newline,
    ACTIONS(234), 2,
      ts_builtin_sym_end,
      anon_sym_new,
    STATE(21), 4,
      sym_add_clause,
      sym_comment,
      sym__blank_line,
      aux_sym_equipment_entry_repeat1,
  [621] = 1,
    ACTIONS(244), 8,
      sym__newline,
      sym__eof,
      anon_sym_COMMA,
      anon_sym_COLON,
      anon_sym_DQUOTE,
      sym_identifier,
      sym_number,
      aux_sym_comment_token1,
  [632] = 1,
    ACTIONS(246), 8,
      sym__newline,
      sym__eof,
      anon_sym_COMMA,
      anon_sym_COLON,
      anon_sym_DQUOTE,
      sym_identifier,
      sym_number,
      aux_sym_comment_token1,
  [643] = 2,
    ACTIONS(250), 1,
      sym_identifier,
    ACTIONS(248), 7,
      sym__newline,
      ts_builtin_sym_end,
      anon_sym_new,
      anon_sym_type,
      anon_sym_using,
      anon_sym_data,
      aux_sym_comment_token1,
  [656] = 1,
    ACTIONS(252), 8,
      sym__newline,
      sym__eof,
      anon_sym_COMMA,
      anon_sym_COLON,
      anon_sym_DQUOTE,
      sym_identifier,
      sym_number,
      aux_sym_comment_token1,
  [667] = 2,
    ACTIONS(256), 1,
      sym_identifier,
    ACTIONS(254), 7,
      sym__newline,
      ts_builtin_sym_end,
      anon_sym_new,
      anon_sym_type,
      anon_sym_using,
      anon_sym_data,
      aux_sym_comment_token1,
  [680] = 2,
    ACTIONS(260), 1,
      sym_identifier,
    ACTIONS(258), 7,
      sym__newline,
      ts_builtin_sym_end,
      anon_sym_new,
      anon_sym_type,
      anon_sym_using,
      anon_sym_data,
      aux_sym_comment_token1,
  [693] = 2,
    ACTIONS(264), 1,
      sym_identifier,
    ACTIONS(262), 7,
      sym__newline,
      ts_builtin_sym_end,
      anon_sym_new,
      anon_sym_type,
      anon_sym_using,
      anon_sym_data,
      aux_sym_comment_token1,
  [706] = 2,
    ACTIONS(268), 1,
      sym_identifier,
    ACTIONS(266), 6,
      sym__newline,
      ts_builtin_sym_end,
      anon_sym_new,
      anon_sym_CanMerge,
      anon_sym_object,
      aux_sym_comment_token1,
  [718] = 3,
    ACTIONS(270), 1,
      sym_identifier,
    STATE(33), 1,
      aux_sym_add_clause_repeat1,
    ACTIONS(273), 5,
      sym__newline,
      sym__eof,
      anon_sym_DQUOTE,
      sym_number,
      aux_sym_comment_token1,
  [732] = 2,
    ACTIONS(277), 1,
      sym_identifier,
    ACTIONS(275), 6,
      sym__newline,
      ts_builtin_sym_end,
      anon_sym_new,
      anon_sym_CanMerge,
      anon_sym_object,
      aux_sym_comment_token1,
  [744] = 2,
    ACTIONS(281), 1,
      sym_identifier,
    ACTIONS(279), 6,
      sym__newline,
      ts_builtin_sym_end,
      anon_sym_new,
      anon_sym_CanMerge,
      anon_sym_object,
      aux_sym_comment_token1,
  [756] = 2,
    ACTIONS(285), 1,
      sym_identifier,
    ACTIONS(283), 5,
      sym__newline,
      ts_builtin_sym_end,
      anon_sym_new,
      anon_sym_add,
      aux_sym_comment_token1,
  [767] = 2,
    ACTIONS(289), 1,
      sym_identifier,
    ACTIONS(287), 5,
      sym__newline,
      ts_builtin_sym_end,
      anon_sym_new,
      anon_sym_add,
      aux_sym_comment_token1,
  [778] = 2,
    ACTIONS(293), 1,
      sym_identifier,
    ACTIONS(291), 5,
      sym__newline,
      ts_builtin_sym_end,
      anon_sym_new,
      anon_sym_CanMerge,
      aux_sym_comment_token1,
  [789] = 5,
    ACTIONS(80), 1,
      aux_sym_comment_token1,
    ACTIONS(295), 1,
      anon_sym_COMMA,
    STATE(34), 1,
      sym__line_end,
    STATE(73), 1,
      sym_trailing_comment,
    ACTIONS(297), 2,
      sym__newline,
      sym__eof,
  [806] = 4,
    ACTIONS(299), 1,
      anon_sym_entry,
    ACTIONS(301), 1,
      anon_sym_treasuretable,
    ACTIONS(303), 1,
      anon_sym_equipment,
    ACTIONS(305), 3,
      anon_sym_spellset,
      anon_sym_itemgroup,
      anon_sym_namegroup,
  [821] = 2,
    ACTIONS(309), 1,
      sym_identifier,
    ACTIONS(307), 5,
      sym__newline,
      ts_builtin_sym_end,
      anon_sym_new,
      anon_sym_add,
      aux_sym_comment_token1,
  [832] = 2,
    ACTIONS(313), 1,
      sym_identifier,
    ACTIONS(311), 5,
      sym__newline,
      ts_builtin_sym_end,
      anon_sym_new,
      anon_sym_CanMerge,
      aux_sym_comment_token1,
  [843] = 1,
    ACTIONS(315), 6,
      sym__newline,
      sym__eof,
      anon_sym_DQUOTE,
      sym_identifier,
      sym_number,
      aux_sym_comment_token1,
  [852] = 2,
    ACTIONS(319), 1,
      sym_identifier,
    ACTIONS(317), 5,
      sym__newline,
      ts_builtin_sym_end,
      anon_sym_new,
      anon_sym_add,
      aux_sym_comment_token1,
  [863] = 2,
    ACTIONS(323), 1,
      sym_identifier,
    ACTIONS(321), 5,
      sym__newline,
      ts_builtin_sym_end,
      anon_sym_new,
      anon_sym_add,
      aux_sym_comment_token1,
  [874] = 2,
    ACTIONS(327), 1,
      sym_identifier,
    ACTIONS(325), 5,
      sym__newline,
      ts_builtin_sym_end,
      anon_sym_new,
      anon_sym_add,
      aux_sym_comment_token1,
  [885] = 3,
    ACTIONS(329), 1,
      anon_sym_COMMA,
    STATE(48), 1,
      aux_sym_comma_values_repeat1,
    ACTIONS(331), 3,
      sym__newline,
      sym__eof,
      aux_sym_comment_token1,
  [897] = 3,
    ACTIONS(333), 1,
      anon_sym_COMMA,
    STATE(48), 1,
      aux_sym_comma_values_repeat1,
    ACTIONS(336), 3,
      sym__newline,
      sym__eof,
      aux_sym_comment_token1,
  [909] = 4,
    ACTIONS(80), 1,
      aux_sym_comment_token1,
    STATE(31), 1,
      sym__line_end,
    STATE(73), 1,
      sym_trailing_comment,
    ACTIONS(338), 2,
      sym__newline,
      sym__eof,
  [923] = 4,
    ACTIONS(80), 1,
      aux_sym_comment_token1,
    STATE(32), 1,
      sym__line_end,
    STATE(73), 1,
      sym_trailing_comment,
    ACTIONS(340), 2,
      sym__newline,
      sym__eof,
  [937] = 4,
    ACTIONS(80), 1,
      aux_sym_comment_token1,
    STATE(27), 1,
      sym__line_end,
    STATE(73), 1,
      sym_trailing_comment,
    ACTIONS(342), 2,
      sym__newline,
      sym__eof,
  [951] = 4,
    ACTIONS(80), 1,
      aux_sym_comment_token1,
    STATE(42), 1,
      sym__line_end,
    STATE(73), 1,
      sym_trailing_comment,
    ACTIONS(344), 2,
      sym__newline,
      sym__eof,
  [965] = 4,
    ACTIONS(80), 1,
      aux_sym_comment_token1,
    STATE(36), 1,
      sym__line_end,
    STATE(73), 1,
      sym_trailing_comment,
    ACTIONS(346), 2,
      sym__newline,
      sym__eof,
  [979] = 4,
    ACTIONS(80), 1,
      aux_sym_comment_token1,
    STATE(46), 1,
      sym__line_end,
    STATE(73), 1,
      sym_trailing_comment,
    ACTIONS(348), 2,
      sym__newline,
      sym__eof,
  [993] = 4,
    ACTIONS(80), 1,
      aux_sym_comment_token1,
    STATE(37), 1,
      sym__line_end,
    STATE(73), 1,
      sym_trailing_comment,
    ACTIONS(350), 2,
      sym__newline,
      sym__eof,
  [1007] = 2,
    ACTIONS(354), 1,
      sym_identifier,
    ACTIONS(352), 4,
      sym__newline,
      ts_builtin_sym_end,
      anon_sym_new,
      aux_sym_comment_token1,
  [1017] = 2,
    ACTIONS(358), 1,
      sym_identifier,
    ACTIONS(356), 4,
      sym__newline,
      ts_builtin_sym_end,
      anon_sym_new,
      aux_sym_comment_token1,
  [1027] = 4,
    ACTIONS(80), 1,
      aux_sym_comment_token1,
    STATE(44), 1,
      sym__line_end,
    STATE(73), 1,
      sym_trailing_comment,
    ACTIONS(360), 2,
      sym__newline,
      sym__eof,
  [1041] = 4,
    ACTIONS(80), 1,
      aux_sym_comment_token1,
    STATE(14), 1,
      sym__line_end,
    STATE(73), 1,
      sym_trailing_comment,
    ACTIONS(362), 2,
      sym__newline,
      sym__eof,
  [1055] = 4,
    ACTIONS(80), 1,
      aux_sym_comment_token1,
    STATE(29), 1,
      sym__line_end,
    STATE(73), 1,
      sym_trailing_comment,
    ACTIONS(364), 2,
      sym__newline,
      sym__eof,
  [1069] = 4,
    ACTIONS(78), 1,
      anon_sym_DQUOTE,
    STATE(63), 1,
      sym_quoted_string,
    STATE(64), 1,
      sym_comma_values,
    ACTIONS(366), 2,
      sym_identifier,
      sym_number,
  [1083] = 4,
    ACTIONS(80), 1,
      aux_sym_comment_token1,
    STATE(30), 1,
      sym__line_end,
    STATE(73), 1,
      sym_trailing_comment,
    ACTIONS(368), 2,
      sym__newline,
      sym__eof,
  [1097] = 3,
    ACTIONS(329), 1,
      anon_sym_COMMA,
    STATE(47), 1,
      aux_sym_comma_values_repeat1,
    ACTIONS(370), 3,
      sym__newline,
      sym__eof,
      aux_sym_comment_token1,
  [1109] = 4,
    ACTIONS(80), 1,
      aux_sym_comment_token1,
    STATE(35), 1,
      sym__line_end,
    STATE(73), 1,
      sym_trailing_comment,
    ACTIONS(372), 2,
      sym__newline,
      sym__eof,
  [1123] = 4,
    ACTIONS(80), 1,
      aux_sym_comment_token1,
    STATE(38), 1,
      sym__line_end,
    STATE(73), 1,
      sym_trailing_comment,
    ACTIONS(374), 2,
      sym__newline,
      sym__eof,
  [1137] = 3,
    ACTIONS(78), 1,
      anon_sym_DQUOTE,
    STATE(67), 1,
      sym_quoted_string,
    ACTIONS(376), 2,
      sym_identifier,
      sym_number,
  [1148] = 1,
    ACTIONS(336), 4,
      sym__newline,
      sym__eof,
      anon_sym_COMMA,
      aux_sym_comment_token1,
  [1155] = 1,
    ACTIONS(378), 3,
      sym__newline,
      sym__eof,
      aux_sym_comment_token1,
  [1161] = 2,
    ACTIONS(78), 1,
      anon_sym_DQUOTE,
    STATE(62), 1,
      sym_quoted_string,
  [1168] = 2,
    ACTIONS(380), 1,
      anon_sym_DQUOTE,
    ACTIONS(382), 1,
      sym_string_content,
  [1175] = 2,
    ACTIONS(78), 1,
      anon_sym_DQUOTE,
    STATE(55), 1,
      sym_quoted_string,
  [1182] = 2,
    ACTIONS(78), 1,
      anon_sym_DQUOTE,
    STATE(54), 1,
      sym_quoted_string,
  [1189] = 1,
    ACTIONS(384), 2,
      sym__newline,
      sym__eof,
  [1194] = 2,
    ACTIONS(78), 1,
      anon_sym_DQUOTE,
    STATE(60), 1,
      sym_quoted_string,
  [1201] = 1,
    ACTIONS(386), 2,
      sym__newline,
      sym__eof,
  [1206] = 2,
    ACTIONS(78), 1,
      anon_sym_DQUOTE,
    STATE(49), 1,
      sym_quoted_string,
  [1213] = 2,
    ACTIONS(78), 1,
      anon_sym_DQUOTE,
    STATE(39), 1,
      sym_quoted_string,
  [1220] = 2,
    ACTIONS(78), 1,
      anon_sym_DQUOTE,
    STATE(50), 1,
      sym_quoted_string,
  [1227] = 2,
    ACTIONS(78), 1,
      anon_sym_DQUOTE,
    STATE(51), 1,
      sym_quoted_string,
  [1234] = 2,
    ACTIONS(388), 1,
      anon_sym_DQUOTE,
    ACTIONS(390), 1,
      sym_string_content,
  [1241] = 2,
    ACTIONS(392), 1,
      anon_sym_DQUOTE,
    STATE(76), 1,
      sym_quoted_string,
  [1248] = 2,
    ACTIONS(78), 1,
      anon_sym_DQUOTE,
    STATE(52), 1,
      sym_quoted_string,
  [1255] = 1,
    ACTIONS(394), 1,
      anon_sym_DQUOTE,
  [1259] = 1,
    ACTIONS(396), 1,
      anon_sym_subtable,
  [1263] = 1,
    ACTIONS(398), 1,
      sym_identifier,
  [1267] = 1,
    ACTIONS(400), 1,
      sym_number,
  [1271] = 1,
    ACTIONS(402), 1,
      anon_sym_category,
  [1275] = 1,
    ACTIONS(246), 1,
      anon_sym_DQUOTE,
  [1279] = 1,
    ACTIONS(252), 1,
      anon_sym_DQUOTE,
  [1283] = 1,
    ACTIONS(404), 1,
      ts_builtin_sym_end,
  [1287] = 1,
    ACTIONS(406), 1,
      anon_sym_DQUOTE,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 38,
  [SMALL_STATE(4)] = 76,
  [SMALL_STATE(5)] = 107,
  [SMALL_STATE(6)] = 138,
  [SMALL_STATE(7)] = 169,
  [SMALL_STATE(8)] = 199,
  [SMALL_STATE(9)] = 229,
  [SMALL_STATE(10)] = 258,
  [SMALL_STATE(11)] = 287,
  [SMALL_STATE(12)] = 316,
  [SMALL_STATE(13)] = 332,
  [SMALL_STATE(14)] = 356,
  [SMALL_STATE(15)] = 372,
  [SMALL_STATE(16)] = 394,
  [SMALL_STATE(17)] = 418,
  [SMALL_STATE(18)] = 450,
  [SMALL_STATE(19)] = 474,
  [SMALL_STATE(20)] = 506,
  [SMALL_STATE(21)] = 529,
  [SMALL_STATE(22)] = 552,
  [SMALL_STATE(23)] = 575,
  [SMALL_STATE(24)] = 598,
  [SMALL_STATE(25)] = 621,
  [SMALL_STATE(26)] = 632,
  [SMALL_STATE(27)] = 643,
  [SMALL_STATE(28)] = 656,
  [SMALL_STATE(29)] = 667,
  [SMALL_STATE(30)] = 680,
  [SMALL_STATE(31)] = 693,
  [SMALL_STATE(32)] = 706,
  [SMALL_STATE(33)] = 718,
  [SMALL_STATE(34)] = 732,
  [SMALL_STATE(35)] = 744,
  [SMALL_STATE(36)] = 756,
  [SMALL_STATE(37)] = 767,
  [SMALL_STATE(38)] = 778,
  [SMALL_STATE(39)] = 789,
  [SMALL_STATE(40)] = 806,
  [SMALL_STATE(41)] = 821,
  [SMALL_STATE(42)] = 832,
  [SMALL_STATE(43)] = 843,
  [SMALL_STATE(44)] = 852,
  [SMALL_STATE(45)] = 863,
  [SMALL_STATE(46)] = 874,
  [SMALL_STATE(47)] = 885,
  [SMALL_STATE(48)] = 897,
  [SMALL_STATE(49)] = 909,
  [SMALL_STATE(50)] = 923,
  [SMALL_STATE(51)] = 937,
  [SMALL_STATE(52)] = 951,
  [SMALL_STATE(53)] = 965,
  [SMALL_STATE(54)] = 979,
  [SMALL_STATE(55)] = 993,
  [SMALL_STATE(56)] = 1007,
  [SMALL_STATE(57)] = 1017,
  [SMALL_STATE(58)] = 1027,
  [SMALL_STATE(59)] = 1041,
  [SMALL_STATE(60)] = 1055,
  [SMALL_STATE(61)] = 1069,
  [SMALL_STATE(62)] = 1083,
  [SMALL_STATE(63)] = 1097,
  [SMALL_STATE(64)] = 1109,
  [SMALL_STATE(65)] = 1123,
  [SMALL_STATE(66)] = 1137,
  [SMALL_STATE(67)] = 1148,
  [SMALL_STATE(68)] = 1155,
  [SMALL_STATE(69)] = 1161,
  [SMALL_STATE(70)] = 1168,
  [SMALL_STATE(71)] = 1175,
  [SMALL_STATE(72)] = 1182,
  [SMALL_STATE(73)] = 1189,
  [SMALL_STATE(74)] = 1194,
  [SMALL_STATE(75)] = 1201,
  [SMALL_STATE(76)] = 1206,
  [SMALL_STATE(77)] = 1213,
  [SMALL_STATE(78)] = 1220,
  [SMALL_STATE(79)] = 1227,
  [SMALL_STATE(80)] = 1234,
  [SMALL_STATE(81)] = 1241,
  [SMALL_STATE(82)] = 1248,
  [SMALL_STATE(83)] = 1255,
  [SMALL_STATE(84)] = 1259,
  [SMALL_STATE(85)] = 1263,
  [SMALL_STATE(86)] = 1267,
  [SMALL_STATE(87)] = 1271,
  [SMALL_STATE(88)] = 1275,
  [SMALL_STATE(89)] = 1279,
  [SMALL_STATE(90)] = 1283,
  [SMALL_STATE(91)] = 1287,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [19] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [22] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(40),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(59),
  [28] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_stat_entry_repeat1, 2, 0, 0),
  [33] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_stat_entry_repeat1, 2, 0, 0),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_stat_entry_repeat1, 2, 0, 0), SHIFT_REPEAT(74),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_stat_entry_repeat1, 2, 0, 0), SHIFT_REPEAT(69),
  [41] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_stat_entry_repeat1, 2, 0, 0), SHIFT_REPEAT(81),
  [44] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_stat_entry_repeat1, 2, 0, 0), SHIFT_REPEAT(59),
  [47] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_stat_entry_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_stat_entry, 2, 0, 0),
  [52] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_stat_entry, 2, 0, 0),
  [54] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [60] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_stat_entry, 2, 0, 0), SHIFT(59),
  [63] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_stat_entry, 2, 0, 0), SHIFT(4),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_stat_entry, 1, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_stat_entry, 1, 0, 0),
  [70] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_stat_entry, 1, 0, 0), SHIFT(59),
  [73] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_stat_entry, 1, 0, 0), SHIFT(5),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_treasure_table, 2, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_treasure_table, 2, 0, 0),
  [90] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_treasure_table, 2, 0, 0), SHIFT(84),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [95] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_treasure_table, 2, 0, 0), SHIFT(59),
  [98] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_treasure_table, 2, 0, 0), SHIFT(11),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_treasure_table, 1, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_treasure_table, 1, 0, 0),
  [105] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_treasure_table, 1, 0, 0), SHIFT(84),
  [108] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_treasure_table, 1, 0, 0), SHIFT(59),
  [111] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_treasure_table, 1, 0, 0), SHIFT(9),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_treasure_table_repeat1, 2, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_treasure_table_repeat1, 2, 0, 0),
  [118] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_treasure_table_repeat1, 2, 0, 0), SHIFT_REPEAT(84),
  [121] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_treasure_table_repeat1, 2, 0, 0), SHIFT_REPEAT(86),
  [124] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_treasure_table_repeat1, 2, 0, 0), SHIFT_REPEAT(59),
  [127] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_treasure_table_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__line_end, 2, 0, 0),
  [132] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__line_end, 2, 0, 0),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_treasure_subtable, 1, 0, 0),
  [136] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_treasure_subtable, 1, 0, 0),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [140] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_treasure_subtable, 1, 0, 0), SHIFT(59),
  [143] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_treasure_subtable, 1, 0, 0), SHIFT(16),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2, 0, 0),
  [148] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 2, 0, 0),
  [150] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_generic_statement_repeat1, 2, 0, 4), SHIFT_REPEAT(25),
  [153] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_generic_statement_repeat1, 2, 0, 4), SHIFT_REPEAT(70),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_generic_statement_repeat1, 2, 0, 4),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_treasure_subtable, 2, 0, 0),
  [160] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_treasure_subtable, 2, 0, 0),
  [162] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_treasure_subtable, 2, 0, 0), SHIFT(59),
  [165] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_treasure_subtable, 2, 0, 0), SHIFT(18),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [174] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_treasure_subtable_repeat1, 2, 0, 0),
  [176] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_treasure_subtable_repeat1, 2, 0, 0),
  [178] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_treasure_subtable_repeat1, 2, 0, 0), SHIFT_REPEAT(87),
  [181] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_treasure_subtable_repeat1, 2, 0, 0), SHIFT_REPEAT(59),
  [184] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_treasure_subtable_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [189] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_named_block, 2, 0, 0),
  [191] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_named_block, 2, 0, 0),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [195] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_named_block, 2, 0, 0), SHIFT(59),
  [198] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_named_block, 2, 0, 0), SHIFT(23),
  [201] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_equipment_entry, 2, 0, 0),
  [203] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_equipment_entry, 2, 0, 0),
  [205] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_equipment_entry, 2, 0, 0), SHIFT(59),
  [208] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_equipment_entry, 2, 0, 0), SHIFT(23),
  [211] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_named_block, 1, 0, 0),
  [213] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_named_block, 1, 0, 0),
  [215] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_named_block, 1, 0, 0), SHIFT(59),
  [218] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_named_block, 1, 0, 0), SHIFT(20),
  [221] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_equipment_entry_repeat1, 2, 0, 0),
  [223] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_equipment_entry_repeat1, 2, 0, 0),
  [225] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_equipment_entry_repeat1, 2, 0, 0), SHIFT_REPEAT(85),
  [228] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_equipment_entry_repeat1, 2, 0, 0), SHIFT_REPEAT(59),
  [231] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_equipment_entry_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [234] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_equipment_entry, 1, 0, 0),
  [236] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_equipment_entry, 1, 0, 0),
  [238] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_equipment_entry, 1, 0, 0), SHIFT(59),
  [241] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_equipment_entry, 1, 0, 0), SHIFT(21),
  [244] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_generic_statement_repeat1, 1, 0, 1),
  [246] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_string, 2, 0, 0),
  [248] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_entry_header, 4, 0, 5),
  [250] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_entry_header, 4, 0, 5),
  [252] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_string, 3, 0, 7),
  [254] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_clause, 3, 0, 8),
  [256] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type_clause, 3, 0, 8),
  [258] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_using_clause, 3, 0, 8),
  [260] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_using_clause, 3, 0, 8),
  [262] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_data_clause, 4, 0, 12),
  [264] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_data_clause, 4, 0, 12),
  [266] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subtable_header, 4, 0, 13),
  [268] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_subtable_header, 4, 0, 13),
  [270] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_add_clause_repeat1, 2, 0, 16), SHIFT_REPEAT(43),
  [273] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_add_clause_repeat1, 2, 0, 16),
  [275] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object_clause, 4, 0, 17),
  [277] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_object_clause, 4, 0, 17),
  [279] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object_clause, 6, 0, 19),
  [281] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_object_clause, 6, 0, 19),
  [283] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_add_clause, 4, 0, 14),
  [285] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_add_clause, 4, 0, 14),
  [287] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_named_block_header, 4, 0, 6),
  [289] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_named_block_header, 4, 0, 6),
  [291] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_merge_clause, 3, 0, 9),
  [293] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_merge_clause, 3, 0, 9),
  [295] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [297] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [299] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [301] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [303] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [305] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [307] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_add_clause, 4, 0, 15),
  [309] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_add_clause, 4, 0, 15),
  [311] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_treasure_table_header, 4, 0, 5),
  [313] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_treasure_table_header, 4, 0, 5),
  [315] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_add_clause_repeat1, 1, 0, 10),
  [317] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_add_clause, 5, 0, 18),
  [319] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_add_clause, 5, 0, 18),
  [321] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_add_clause, 3, 0, 11),
  [323] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_add_clause, 3, 0, 11),
  [325] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_equipment_header, 4, 0, 5),
  [327] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_equipment_header, 4, 0, 5),
  [329] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [331] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comma_values, 2, 0, 0),
  [333] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_comma_values_repeat1, 2, 0, 0), SHIFT_REPEAT(66),
  [336] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_comma_values_repeat1, 2, 0, 0),
  [338] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [340] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [342] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [344] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [346] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [348] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [350] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [352] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_generic_statement, 2, 0, 2),
  [354] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_generic_statement, 2, 0, 2),
  [356] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_generic_statement, 3, 0, 3),
  [358] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_generic_statement, 3, 0, 3),
  [360] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [362] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [364] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [366] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [368] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [370] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comma_values, 1, 0, 0),
  [372] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [374] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [376] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [378] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arguments, 1, 0, 0),
  [380] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [382] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [384] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [386] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_trailing_comment, 1, 0, 0),
  [388] = {.entry = {.count = 1, .reusable = false}}, SHIFT(88),
  [390] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [392] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [394] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [396] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [398] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [400] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [402] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [404] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [406] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token__newline = 0,
  ts_external_token__eof = 1,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__newline] = sym__newline,
  [ts_external_token__eof] = sym__eof,
};

static const bool ts_external_scanner_states[3][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__newline] = true,
    [ts_external_token__eof] = true,
  },
  [2] = {
    [ts_external_token__newline] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_bg3_stats_external_scanner_create(void);
void tree_sitter_bg3_stats_external_scanner_destroy(void *);
bool tree_sitter_bg3_stats_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_bg3_stats_external_scanner_serialize(void *, char *);
void tree_sitter_bg3_stats_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_bg3_stats(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_bg3_stats_external_scanner_create,
      tree_sitter_bg3_stats_external_scanner_destroy,
      tree_sitter_bg3_stats_external_scanner_scan,
      tree_sitter_bg3_stats_external_scanner_serialize,
      tree_sitter_bg3_stats_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
    .name = "bg3_stats",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 7,
      .patch_version = 2,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
